---

- name: add plugin for diagram
  shell : "grafana-cli plugins install {{ item }}"
  with_items: "{{ grafana_plugins }}"
  changed_when: false

- name: Flush handlers grafana plugins
  meta: flush_handlers
