---

- name: add admin users on Debian Family servers
  user:
    name: "{{ admin_username }}"
    groups: sudo
    append: yes
    shell: /bin/bash
    password: "{{ password_admin_icm | password_hash('sha512') }}"
  register: result
  changed_when: false
  when: ansible_os_family == "Debian"

- name: add admin users on CentOS servers
  user:
    name: "{{ admin_username }}"
    groups: wheel
    append: yes
    shell: /bin/bash
    password: "{{ password_admin_icm | password_hash('sha512') }}"
  register: result
  changed_when: false
  when: ansible_distribution == "CentOS"

- name: need run again with new password
  debug:
    msg: "You must run ansible again with the new password (cf vault (group all) if you need)"