---

- name: add distribution-specific variables
  include_vars: "update/{{ ansible_distribution }}.yml"

- name: add Debian Wheezy workaround
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "wheezy")

- name: install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
    update_cache: yes

- name: create APT auto-upgrades configuration
  template:
    src: update/auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration (for security)
  template:
    src: update/unattended-upgrades-security.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades-security
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration (for all packages)
  template:
    src: update/unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644