{
 "title": "AD and DNS",
 "description": "Active Directory and DNS Dashboard using Prometheus windows_Exporter ",
 "tags": [
  "windows",
  "windows_exporter",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.btp-consultants.fr/wp-content/uploads/2018/11/logo_b.png\" alt=\"logo btp\">"
   }
  },
  {
   "title": "Servers",
   "type": "table",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(windows_cpu_time_total{instance=~\".*DC0.*\"}[5m]))"
    },
    {
     "expr": "(max(windows_os_physical_memory_free_bytes{instance=~\".*DC0.*\"}) by (instance))/1000/1000/1000"
    },
    {
     "expr": "(windows_os_info{instance=~\".*DC0.*\"})"
    },
    {
     "expr": "(windows_cs_logical_processors{instance=~\".*DC0.*\"})"
    }
   ]
  },
  {
   "title": "Rate of total IOPS for C:\\",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_reads_total{volume=\"C:\",instance=~\".*DC0.*\"}[2m]) + rate(windows_logical_disk_writes_total{volume=\"C:\",instance=~\".*DC0.*\"}[2m])\r",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rate of read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{volume=~\"C:\",instance=~\".*DC0.*\"}[5m])\r",
     "legendFormat": "read {{ instance }}"
    }
   ]
  },
  {
   "title": "Rate of write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{volume=~\"C:\",instance=~\".*DC0.*\"}[5m])\r",
     "legendFormat": "write {{ instance }}"
    }
   ]
  },
  {
   "title": "MemoryUsage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_os_visible_memory_bytes{instance=~\".*DC0.*\"}\t- windows_os_physical_memory_free_bytes{instance=~\".*DC0.*\"}",
     "legendFormat": "physical {{instance}}"
    },
    {
     "expr": "windows_os_virtual_memory_bytes{instance=~\".*DC0.*\"} - windows_os_virtual_memory_free_bytes{instance=~\".*DC0.*\"}\t",
     "legendFormat": "virtual {{instance}}"
    }
   ]
  },
  {
   "title": "MemoryFree",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_os_virtual_memory_free_bytes{instance=~\".*DC0.*\"}\t",
     "legendFormat": "virtual {{ instance }}"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=~\".*DC0.*\"}\t",
     "legendFormat": "physical {{ instance }}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "DNS Queries",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(windows_dns_queries_total{protocol=\"udp\"}[5m]))"
    }
   ]
  },
  {
   "title": "DNS Queries/Sec",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(windows_dns_queries_total{protocol=\"udp\"}[5m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 27 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[5m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections/Sec",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[5m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 27 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(windows_ad_ldap_searches_total{}[5m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches / Sec",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 27 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(windows_ad_ldap_searches_total{}[5m]))"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Queries/Responses",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_dns_queries_total{}[5m])",
       "legendFormat": "in-{{protocol}} ({{instance}})"
      },
      {
       "expr": "-delta(windows_dns_responses_total{}[5m])",
       "legendFormat": "out-{{protocol}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Recursive Queries / Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_dns_recursive_query_failures_total[5m])",
       "legendFormat": "failures ({{instance}})"
      },
      {
       "expr": "delta(windows_dns_recursive_queries_total[5m])",
       "legendFormat": "queries ({{instance}})"
      },
      {
       "expr": "delta(windows_dns_recursive_query_send_timeouts_total[5m])",
       "legendFormat": "sent timeouts ({{instance}})"
      }
     ]
    }
   ]
  },
  { "title": "AD Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Pending Syncronisations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(windows_ad_replication_pending_synchronizations{})"
    }
   ]
  },
  {
   "title": "Pending Operations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(windows_ad_replication_pending_operations{})"
    }
   ]
  },
  {
   "title": "Inbound Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_inbound_objects_updated_total{}[5m])",
     "legendFormat": "objects ({{instance}})"
    },
    {
     "expr": "delta(windows_ad_replication_inbound_properties_updated_total{}[5m])",
     "legendFormat": "properties ({{instance}})"
    }
   ]
  },
  {
   "title": "Intrasite Replication Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_data_intrasite_bytes_total{direction=\"inbound\"}[5m])",
     "legendFormat": "inbound ({{instance}})"
    },
    {
     "expr": "-delta(windows_ad_replication_data_intrasite_bytes_total{direction=\"outbound\"}[5m])",
     "legendFormat": "outbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Intersite Replication Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[5m])",
     "legendFormat": "inbound ({{instance}})"
    },
    {
     "expr": "-delta(windows_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[5m])",
     "legendFormat": "outbound ({{instance}})"
    }
   ]
  },
  {
   "title": "AD Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "AD Operations (Detailed)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_directory_operations_total{}[5m])",
       "legendFormat": "{{origin}}-{{operation}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Directory Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_database_operations_total{}[5m])",
       "legendFormat": "{{operation}} ({{instance}})"
      }
     ]
    }
   ]
  },
  { "title": "AD Binds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "AD Bind",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_binds_total{}[5m])",
     "legendFormat": "{{bind_method}} ({{instance}})"
    }
   ]
  },
  { "title": "AD LDAP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "LDAP Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[5m])",
     "legendFormat": "Opened ({{instance}})"
    },
    {
     "expr": "-(delta(windows_ad_ldap_closed_connections_total{}[5m]))",
     "legendFormat": "Closed ({{instance}})"
    }
   ]
  },
  { "title": "AD Heatmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "LDAP connections HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[5m])"
    }
   ]
  },
  {
   "title": "LDAP Searches",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "delta(windows_ad_ldap_searches_total[5m])"
    }
   ]
  },
  {
   "title": "AD LDAP Searches/Updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDAP Searches/Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_writes_total{}[5m])",
       "legendFormat": "Writes ({{instance}})"
      },
      {
       "expr": "-delta(windows_ad_ldap_searches_total{}[5m])",
       "legendFormat": "Searches ({{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "DNS Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "DNS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(windows_dns_memory_used_bytes_total{}[5m])",
     "legendFormat": "{{area}} ({{instance}})"
    }
   ]
  },
  { "title": "DNS Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_dynamic_updates_received_total[5m])",
     "legendFormat": "{{operation}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_dynamic_updates_failures_total[5m])",
     "legendFormat": "{{reason}} ({{instance}})"
    }
   ]
  }
 ]
}