{
 "title": "Veeam-SRVSQYSAUV02",
 "tags": [
  "windows",
  "windows_exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Repository Free Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "REPO_Default_Backup_Repository" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "SRVSQYSAUV02-I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" }
      ],
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "successful backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "successJobBk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "warning backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "warningJobBk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "failed backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "failedJobBk" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "running backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "runningJobBk" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "SRVSQYSAUV02-CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       { "params": [ "user_time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       { "params": [ "processor_time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "SRVSQYSAUV02-RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       { "params": [ "available_bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Nonpaged_Bytes" ], "type": "field" },
       { "params": [ "nonpaged_bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Paged_Bytes" ], "type": "field" },
       { "params": [ "paged_bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "successful phys backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "successJobBkPhys" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "warning phys backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "warningJobBkPhys" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "failed phys backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "failedJobBkPhys" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "running physical backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "runningJobBkPhys" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "SRVSQYSAUV02-NETWORK-NIC1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       { "params": [ "bytes_received" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Broadcom NetXtreme E-Series Advanced Dual-port 10GBASE-T Ethernet LOM"
      }
     ]
    }
   ]
  },
  {
   "title": "SRVSQYSAUV02-NETWORK-NIC2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       { "params": [ "bytes_received" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Broadcom NetXtreme E-Series Advanced Dual-port 10GBASE-T Ethernet LOM _2"
      }
     ]
    }
   ]
  },
  {
   "title": "successful tape backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "successTapeBk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "warning tape backups ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "warningTapeBk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "failed tape backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "failedTapeBk" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  },
  {
   "title": "running  tape backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "runningTapeBk" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRVSQYSAUV02" }
     ]
    }
   ]
  }
 ]
}