{
 "title": "System Monitoring",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.btp-consultants.fr/wp-content/uploads/2018/11/logo_b.png\" alt=\"logo btp\">"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 17, "x": 7, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-weight: bold;text-align:right;\">BTP Monitoring</h1>"
   }
  },
  {
   "title": "Servers",
   "type": "table",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\"}[10m])) * 100)"
    },
    {
     "expr": "max by (instance) (irate(node_load1{job=\"node_exporter\"}[5m]) * 100)"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter\"}) by (cpu,instance)) by (instance)"
    },
    {
     "expr": "(max(node_memory_MemTotal_bytes{job=\"node_exporter\"}) by (instance))/1000/1000/1000"
    },
    {
     "expr": "(node_time_seconds{job=\"node_exporter\"} - node_boot_time_seconds{job=\"node_exporter\"})/60/60/24"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Espace disponible /home",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_avail_bytes{job=\"node_exporter\",device!~'rootfs',mountpoint=\"/home\"}) by (instance))/1024/1024/1024",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Espace disponible /",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_avail_bytes{job=\"node_exporter\",device!~'rootfs',mountpoint=\"/\"}) by (instance))/1024/1024/1024",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MemoryUsage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\"} - node_memory_MemFree_bytes{job=\"node_exporter\"} - (node_memory_Cached_bytes{job=\"node_exporter\"} + node_memory_Buffers_bytes{job=\"node_exporter\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MemoryFree",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\"}) by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\"}-container_memory_usage_bytes{name!=\"\"})by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\"}) by (name)"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}