{
 "title": "System Monitoring Windows",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.btp-consultants.fr/wp-content/uploads/2018/11/logo_b.png\" alt=\"logo btp\">"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 17, "x": 7, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-weight: bold;text-align:right;\">BTP Monitoring</h1>"
   }
  },
  {
   "title": "Servers",
   "type": "table",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(windows_cpu_time_total[5m]))"
    },
    {
     "expr": "(max(windows_os_physical_memory_free_bytes) by (instance))/1000/1000/1000"
    },
    { "expr": "(windows_os_info)" },
    {
     "expr": "(windows_cs_logical_processors)"
    }
   ]
  },
  {
   "title": "Rate of total IOPS for C:\\",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_reads_total{volume=\"C:\"}[2m]) + rate(windows_logical_disk_writes_total{volume=\"C:\"}[2m])\r",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rate of read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{volume=~\"C:\"}[5m])",
     "legendFormat": "read {{ instance }}"
    }
   ]
  },
  {
   "title": "Rate of write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{volume=~\"C:\"}[5m])\r",
     "legendFormat": "write {{ instance }}"
    }
   ]
  },
  {
   "title": "MemoryUsage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_os_visible_memory_bytes\t- windows_os_physical_memory_free_bytes",
     "legendFormat": "physical {{instance}}"
    },
    {
     "expr": "windows_os_virtual_memory_bytes - windows_os_virtual_memory_free_bytes\t",
     "legendFormat": "virtual {{instance}}"
    }
   ]
  },
  {
   "title": "MemoryFree",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_os_virtual_memory_free_bytes\t",
     "legendFormat": "virtual {{ instance }}"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes\t",
     "legendFormat": "physical {{ instance }}"
    }
   ]
  }
 ]
}