{
 "title": "Urls Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "target",
    "query": "label_values(probe_success, site)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.btp-consultants.fr/wp-content/uploads/2018/11/logo_b.png\" alt=\"logo btp\">"
   }
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(probe_success == 0) or vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 2 },
   "options": {
    "content": "<h1 style=\"font-weight: bold;text-align:right;\">BTP Monitoring</h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_success == 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Urls Monitoring",
   "type": "table",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "probe_success{site=~\"$target\"}"
    },
    {
     "expr": "probe_http_ssl{site=~\"$target\"}"
    },
    {
     "expr": "probe_http_status_code{site=~\"$target\"}"
    },
    {
     "expr": "probe_duration_seconds{site=~\"$target\"}*1000"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=\"blackbox\"} - time())/60/60/24"
    },
    { "expr": "probe_tls_version_info" }
   ]
  },
  {
   "title": "probe duration time during period",
   "type": "graph",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{site=~\"$target\"}*1000",
     "legendFormat": "{{site}}"
    }
   ]
  }
 ]
}