{
 "title": "AffectPlus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "[STG] AffectPlus - Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cpu Utilisation Conteneur",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "STG-API", "ServiceName": "STG-affectplus-frontend" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Memory Utilisation Conteneur",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "STG-API", "ServiceName": "*" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "[STG] RDS Database MariaDB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "affectation-des-missions-dev" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "region": "eu-west-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Queries",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "metricName": "Queries", "namespace": "AWS/RDS", "region": "eu-west-1", "statistics": [ "Average" ] }
     ]
    }
   ]
  },
  {
   "title": "[PRD] AffectPlus - Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "[PRD] AffectPlus - Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "[PRD] RDS Database MariaDB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  }
 ]
}