---
# tasks file for prometheus_dock

- name: Add repository (Centos)
  yum_repository:
    name: prometheus
    description: Prometheus ICM main repo
    baseurl: http://nexus01.icm-institute.org/repo/prometheus/
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: check if essential package is present (Debian)
  apt:
    name: prometheus
    state: present
  when: ansible_os_family == "Debian"

- name: check if essential package is present (CentOS & Amazon Linux)
  become: true
  yum:
    name: prometheus
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: defautl args for systemd
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: create rules directory if alertmanager
  file:
    dest: "/etc/prometheus/rules"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  when: prometheus_alermanager_active == true

- name: create prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: restart_prometheus

- name: copy rules files if alertmanager active
  copy:
    src: "{{ item}}"
    dest: "{{ prometheus_dir_configuration }}/rules/"
    mode: 0755
    owner: prometheus
    group: prometheus
  with_fileglob:
  - "*rules.yml"
  notify: reload_prometheus

- name: start prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Flush handlers prometheus role
  meta: flush_handlers
